/**
 * CAP-061 / story 017-006: PR body generator.
 *
 * Pure function. Given a job + its session + cost metadata,
 * renders a markdown PR body that captures the prompt, outcome
 * metrics, and a link to the recording. The caller stores the
 * rendered body via `octokit.pulls.update({body})` (or uses it
 * when calling `octokit.pulls.create`).
 *
 * Keeping this pure means:
 *   - Contract tests against fixed input → fixed output.
 *   - The format is easy to iterate on without touching the hub's
 *     octokit integration layer.
 */

export interface PrBodyInput {
  /** The job's triggering prompt. Truncated at 2000 chars. */
  prompt: string;
  /** Number of files the agent modified. */
  filesChanged?: number;
  /** Whether `npm test` (or equivalent) exited 0. */
  testsPassed?: boolean | null;
  /** Total USD spent on the session. */
  costUsd?: number;
  /** Session wall-clock duration in seconds. */
  durationSeconds?: number;
  /** Hub-relative session detail URL so reviewers can see the replay. */
  sessionUrl?: string;
  /** Optional additional context block (e.g. error messages). */
  additionalContext?: string;
  /** Hub version string for auditability. */
  hubVersion?: string;
  /** Tool name used to generate the PR (default "Claude HQ"). */
  toolName?: string;
}

const PROMPT_MAX_CHARS = 2000;
const CONTEXT_MAX_CHARS = 1500;

export function renderPrBody(input: PrBodyInput): string {
  const lines: string[] = [];
  const toolName = input.toolName ?? 'Claude HQ';

  lines.push(`## ${toolName} — automated change`);
  lines.push('');

  // Prompt block
  lines.push('### Prompt');
  lines.push('');
  lines.push('```');
  lines.push(truncate(input.prompt, PROMPT_MAX_CHARS));
  lines.push('```');
  lines.push('');

  // Metrics table — only render rows that have a value.
  const rows: Array<[string, string]> = [];
  if (typeof input.filesChanged === 'number') {
    rows.push(['Files changed', String(input.filesChanged)]);
  }
  if (input.testsPassed !== undefined && input.testsPassed !== null) {
    rows.push(['Tests', input.testsPassed ? '✅ passed' : '❌ failed']);
  }
  if (typeof input.costUsd === 'number') {
    rows.push(['Cost', `$${input.costUsd.toFixed(4)}`]);
  }
  if (typeof input.durationSeconds === 'number') {
    rows.push(['Duration', formatDuration(input.durationSeconds)]);
  }

  if (rows.length > 0) {
    lines.push('### Metrics');
    lines.push('');
    lines.push('| Metric | Value |');
    lines.push('| --- | --- |');
    for (const [k, v] of rows) lines.push(`| ${k} | ${v} |`);
    lines.push('');
  }

  // Recording link
  if (input.sessionUrl) {
    lines.push(`### Session`);
    lines.push('');
    lines.push(`[▶ View session replay](${input.sessionUrl})`);
    lines.push('');
  }

  // Additional context
  if (input.additionalContext && input.additionalContext.trim().length > 0) {
    lines.push('### Additional context');
    lines.push('');
    lines.push('```');
    lines.push(truncate(input.additionalContext, CONTEXT_MAX_CHARS));
    lines.push('```');
    lines.push('');
  }

  // Footer with provenance
  lines.push('---');
  const versionSuffix = input.hubVersion ? ` v${input.hubVersion}` : '';
  lines.push(`_Generated by ${toolName}${versionSuffix}. This PR is safe to close if unwanted._`);

  return lines.join('\n');
}

function truncate(text: string, max: number): string {
  if (text.length <= max) return text;
  return text.slice(0, max) + `\n…truncated (${text.length - max} more chars)`;
}

function formatDuration(seconds: number): string {
  if (seconds < 60) return `${seconds}s`;
  const m = Math.floor(seconds / 60);
  const s = Math.floor(seconds % 60);
  if (m < 60) return `${m}m ${s}s`;
  const h = Math.floor(m / 60);
  const rem = m % 60;
  return `${h}h ${rem}m ${s}s`;
}
