import { describe, it, expect } from 'vitest';
import { renderPrBody } from '../pr-body.js';

// CAP-061 / story 017-006: PR body generator.

describe('renderPrBody', () => {
  it('renders a complete body with every field populated', () => {
    const body = renderPrBody({
      prompt: 'Fix the login bug',
      filesChanged: 3,
      testsPassed: true,
      costUsd: 0.0125,
      durationSeconds: 142,
      sessionUrl: 'https://hq.example/sessions/abc',
      hubVersion: '0.1.0',
    });

    expect(body).toContain('## Claude HQ');
    expect(body).toContain('Fix the login bug');
    expect(body).toContain('| Files changed | 3 |');
    expect(body).toContain('| Tests | ✅ passed |');
    expect(body).toContain('| Cost | $0.0125 |');
    expect(body).toContain('| Duration | 2m 22s |');
    expect(body).toContain('[▶ View session replay](https://hq.example/sessions/abc)');
    expect(body).toContain('_Generated by Claude HQ v0.1.0');
  });

  it('omits the metrics table when no metrics are provided', () => {
    const body = renderPrBody({ prompt: 'Hello' });
    expect(body).not.toContain('### Metrics');
    expect(body).not.toContain('| Metric |');
  });

  it('renders "❌ failed" when testsPassed is false', () => {
    const body = renderPrBody({ prompt: 'x', testsPassed: false });
    expect(body).toContain('| Tests | ❌ failed |');
  });

  it('omits tests row when testsPassed is null', () => {
    const body = renderPrBody({ prompt: 'x', testsPassed: null });
    expect(body).not.toContain('| Tests |');
  });

  it('truncates a prompt longer than 2000 chars', () => {
    const long = 'a'.repeat(2500);
    const body = renderPrBody({ prompt: long });
    // 2000-char head + truncation marker
    expect(body).toContain('truncated (500 more chars)');
    expect(body.split('```')[1]?.length).toBeLessThan(2100);
  });

  it('formats durations under a minute as Ns', () => {
    const body = renderPrBody({ prompt: 'x', durationSeconds: 45 });
    expect(body).toContain('| Duration | 45s |');
  });

  it('formats durations under an hour as Mm Ss', () => {
    const body = renderPrBody({ prompt: 'x', durationSeconds: 125 });
    expect(body).toContain('| Duration | 2m 5s |');
  });

  it('formats durations over an hour as Hh Mm Ss', () => {
    const body = renderPrBody({ prompt: 'x', durationSeconds: 3725 });
    expect(body).toContain('| Duration | 1h 2m 5s |');
  });

  it('honors additionalContext when provided', () => {
    const body = renderPrBody({
      prompt: 'x',
      additionalContext: 'Error: test suite flaked on macOS',
    });
    expect(body).toContain('### Additional context');
    expect(body).toContain('Error: test suite flaked on macOS');
  });

  it('omits additionalContext section when blank', () => {
    const body = renderPrBody({ prompt: 'x', additionalContext: '   ' });
    expect(body).not.toContain('### Additional context');
  });

  it('honors custom toolName', () => {
    const body = renderPrBody({ prompt: 'x', toolName: 'MyAgent' });
    expect(body).toContain('## MyAgent');
    expect(body).toContain('_Generated by MyAgent');
  });

  it('cost rounding shows 4 decimal places', () => {
    const body = renderPrBody({ prompt: 'x', costUsd: 0.012345678 });
    expect(body).toContain('| Cost | $0.0123 |');
  });
});
